replicaCount: 24

image:
  repository: anandswarup44/intelchain-node
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "1.5"
    memory: "3Gi"
  requests:
    cpu: "1"
    memory: "2Gi"
ingress:
  enabled: false  # Change to true if you want to enable ingress
  className: ""   # Optional, define if required
  annotations: {}
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

service:
  type: ClusterIP
  ports:
    rpc: 9500
    p2p: 9000

dataPersistence:
  enabled: true
  storageClass: "standard"
  size: 5Gi

network:
  bootnodes: "/ip4/64.227.157.72/tcp/9876/p2p/QmT1RorLMMW6Zj54zQCyKjXBb3fciHY33o4UQbeMAh5JD6"
  p2pMuxer: "yamux"
  maxConnPerIP: 100
  blocksPerEpoch: 16
  blocksPerEpochV2: 16
  syncDownloader: true
  stagedSync: true
  dns: false
  dnsClient: false

logging:
  verbosity: 5
serviceAccount:
  create: true
  name: validator-node-sa
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

    
containerPort: 9500

nodeConfig:
  ip: "127.0.0.1"
  portBase: 9000
  dbDirBase: "./../db"
  keyDir: "/.itc"
  blskeys:
    - "f47238daef97d60deedbde5302d05dea5de67608f11f406576e363661f7dcbc4a1385948549b31a6c70f6fde8a391486.key"
    - "b3f59d4c7de3f60fa7d1a70c7d29a6c70f6fde8a391486.key"
    -  "c472cda1c097d60deedbde5302d05dea8f406576e363661f7dcbc4a1385948549b31a6c70f6fde8a391486.key"
    - "lastkeyfile.key"
  # Add all 24 keys in order

