
apiVersion: v1
kind: ConfigMap
metadata:
  name: validator-config
data:
  {{- range $index, $key := .Values.nodeConfig.blskeys }}
  {{ $key }}: |
    # Contents of the key file or instructions to populate it
  {{- end }}
