apiVersion: v1
kind: ConfigMap
metadata:
  name: validator-config
data:
  config-0.yaml: |
    validator_id: 0
    p2p_port: 9000
    rpc_port: 8545
    ip: 127.0.0.1
    port: 9100
    key: /tmp/127.0.0.1-9100.key
    db_dir: /db-127.0.0.1-9100
    blskey_file: /.itc/key-0.key
  
  config-1.yaml: |
    validator_id: 1
    p2p_port: 9001
    rpc_port: 8546
    ip: 127.0.0.1
    port: 9101
    key: /tmp/127.0.0.1-9101.key
    db_dir: /db-127.0.0.1-9101
    blskey_file: /.itc/key-1.key
  
  config-2.yaml: |
    validator_id: 2
    p2p_port: 9002
    rpc_port: 8547
    ip: 127.0.0.1
    port: 9102
    key: /tmp/127.0.0.1-9102.key
    db_dir: /db-127.0.0.1-9102
    blskey_file: /.itc/key-2.key

  config-3.yaml: |
    validator_id: 3
    p2p_port: 9003
    rpc_port: 8548
    ip: 127.0.0.1
    port: 9103
    key: /tmp/127.0.0.1-9103.key
    db_dir: /db-127.0.0.1-9103
    blskey_file: /.itc/key-3.key

  config-4.yaml: |
    validator_id: 4
    p2p_port: 9004
    rpc_port: 8549
    ip: 127.0.0.1
    port: 9104
    key: /tmp/127.0.0.1-9104.key
    db_dir: /db-127.0.0.1-9104
    blskey_file: /.itc/key-4.key

  config-5.yaml: |
    validator_id: 5
    p2p_port: 9005
    rpc_port: 8550
    ip: 127.0.0.1
    port: 9105
    key: /tmp/127.0.0.1-9105.key
    db_dir: /db-127.0.0.1-9105
    blskey_file: /.itc/key-5.key

  config-6.yaml: |
    validator_id: 6
    p2p_port: 9006
    rpc_port: 8551
    ip: 127.0.0.1
    port: 9106
    key: /tmp/127.0.0.1-9106.key
    db_dir: /db-127.0.0.1-9106
    blskey_file: /.itc/key-6.key

  config-7.yaml: |
    validator_id: 7
    p2p_port: 9007
    rpc_port: 8552
    ip: 127.0.0.1
    port: 9107
    key: /tmp/127.0.0.1-9107.key
    db_dir: /db-127.0.0.1-9107
    blskey_file: /.itc/key-7.key

  config-8.yaml: |
    validator_id: 8
    p2p_port: 9008
    rpc_port: 8553
    ip: 127.0.0.1
    port: 9108
    key: /tmp/127.0.0.1-9108.key
    db_dir: /db-127.0.0.1-9108
    blskey_file: /.itc/key-8.key

  config-9.yaml: |
    validator_id: 9
    p2p_port: 9009
    rpc_port: 8554
    ip: 127.0.0.1
    port: 9109
    key: /tmp/127.0.0.1-9109.key
    db_dir: /db-127.0.0.1-9109
    blskey_file: /.itc/key-9.key

  config-10.yaml: |
    validator_id: 10
    p2p_port: 9010
    rpc_port: 8555
    ip: 127.0.0.1
    port: 9110
    key: /tmp/127.0.0.1-9110.key
    db_dir: /db-127.0.0.1-9110
    blskey_file: /.itc/key-10.key

  config-11.yaml: |
    validator_id: 11
    p2p_port: 9011
    rpc_port: 8556
    ip: 127.0.0.1
    port: 9111
    key: /tmp/127.0.0.1-9111.key
    db_dir: /db-127.0.0.1-9111
    blskey_file: /.itc/key-11.key

  config-12.yaml: |
    validator_id: 12
    p2p_port: 9012
    rpc_port: 8557
    ip: 127.0.0.1
    port: 9112
    key: /tmp/127.0.0.1-9112.key
    db_dir: /db-127.0.0.1-9112
    blskey_file: /.itc/key-12.key

  config-13.yaml: |
    validator_id: 13
    p2p_port: 9013
    rpc_port: 8558
    ip: 127.0.0.1
    port: 9113
    key: /tmp/127.0.0.1-9113.key
    db_dir: /db-127.0.0.1-9113
    blskey_file: /.itc/key-13.key

  config-14.yaml: |
    validator_id: 14
    p2p_port: 9014
    rpc_port: 8559
    ip: 127.0.0.1
    port: 9114
    key: /tmp/127.0.0.1-9114.key
    db_dir: /db-127.0.0.1-9114
    blskey_file: /.itc/key-14.key

  config-15.yaml: |
    validator_id: 15
    p2p_port: 9015
    rpc_port: 8560
    ip: 127.0.0.1
    port: 9115
    key: /tmp/127.0.0.1-9115.key
    db_dir: /db-127.0.0.1-9115
    blskey_file: /.itc/key-15.key

  config-16.yaml: |
    validator_id: 16
    p2p_port: 9016
    rpc_port: 8561
    ip: 127.0.0.1
    port: 9116
    key: /tmp/127.0.0.1-9116.key
    db_dir: /db-127.0.0.1-9116
    blskey_file: /.itc/key-16.key

  config-17.yaml: |
    validator_id: 17
    p2p_port: 9017
    rpc_port: 8562
    ip: 127.0.0.1
    port: 9117
    key: /tmp/127.0.0.1-9117.key
    db_dir: /db-127.0.0.1-9117
    blskey_file: /.itc/key-17.key

  config-18.yaml: |
    validator_id: 18
    p2p_port: 9018
    rpc_port: 8563
    ip: 127.0.0.1
    port: 9118
    key: /tmp/127.0.0.1-9118.key
    db_dir: /db-127.0.0.1-9118
    blskey_file: /.itc/key-18.key

  config-19.yaml: |
    validator_id: 19
    p2p_port: 9019
    rpc_port: 8564
    ip: 127.0.0.1
    port: 9119
    key: /tmp/127.0.0.1-9119.key
    db_dir: /db-127.0.0.1-9119
    blskey_file: /.itc/key-19.key

  config-20.yaml: |
    validator_id: 20
    p2p_port: 9020
    rpc_port: 8565
    ip: 127.0.0.1
    port: 9120
    key: /tmp/127.0.0.1-9120.key
    db_dir: /db-127.0.0.1-9120
    blskey_file: /.itc/key-20.key

  config-21.yaml: |
    validator_id: 21
    p2p_port: 9021
    rpc_port: 8566
    ip: 127.0.0.1
    port: 9121
    key: /tmp/127.0.0.1-9121.key
    db_dir: /db-127.0.0.1-9121
    blskey_file: /.itc/key-21.key

  config-22.yaml: |
    validator_id: 22
    p2p_port: 9022
    rpc_port: 8567
    ip: 127.0.0.1
    port: 9122
    key: /tmp/127.0.0.1-9122.key
    db_dir: /db-127.0.0.1-9122
    blskey_file: /.itc/key-22.key

  config-23.yaml: |
    validator_id: 23
    p2p_port: 9023
    rpc_port: 8568
    ip: 127.0.0.1
    port: 9123
    key: /tmp/127.0.0.1-9123.key
    db_dir: /db-127.0.0.1-9123
    blskey_file: /.itc/key-23.key