apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rpc
spec:
  type: LoadBalancer
  ports:
    - port: 9500
      targetPort: 9500
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
