apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-validator
  labels:
    app: validator
spec:
  clusterIP: None  # Headless service for stateful pods
  ports:
    - name: p2p
      port: 30303
    - name: rpc
      port: 8545
  selector:
    app: validator
