apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-validator
  labels:
    app: validator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: validator
  serviceName: {{ .Release.Name }}-validator
  template:
    metadata:
      labels:
        app: validator
    spec:
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      containers:
        - name: validator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
            - "/bin/sh"
            - "-c"
            - |
              ./intelchain {{ range .Values.commonFlags }}{{ . }} {{ end }} $(CONFIG_FLAGS)
          env:
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CONFIG_FLAGS
              valueFrom:
                configMapKeyRef:
                  name: validator-config
                  key: validator-$(STATEFULSET_INDEX)  # Maps to the correct key
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.storage.size }}
